#pragma once
#include "src/doublevec_src/doublevec.hpp"
#include "src/matrix_src/matrix.hpp"
#include "src/complex_src/complex_number.hpp"
#include "src/machine_learning_src/k_means.hpp"
#include "src/machine_learning_src/linear_regression.hpp"
#include "src/utilities_src/utility_functions.hpp"
#include "src/utilities_src/parameterized_function.hpp"
#include "src/machine_learning_src/weighted_avg_regression.hpp"